config/routes.rb
Demo::Application.routes.draw do
	get "welcome/say_hello"=>"welcome#say"
        get "index" => "index#welcome"
	root :to => "welcome#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def say
	end
	def index
	end
        def pdf_render
	  respond_to do |format|
  	     format.pdf {
   		input_filename = Rails.root.join('input.pdf')

    		page_count = PDF::Reader.new(input_filename).page_count

    		file = Prawn::Document.new(:skip_page_creation => true) do |pdf|

      		page_count.times do |num|
        	pdf.start_new_page(:template => input_filename, :template_page => num+1)
        	pdf.move_down(700)
        	pdf.text('FOOTER TEXT')
      		end

    	   end
    	   send_data file.render
  	}
	end
   	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p>sdfgsd <%= Time.now%> </p>

<p><%=link_to 'hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello,world</h1>

<h1><%=link_to "gome", root_path %></h1>

prawn::document.generate('hello.pdf') do |pdf|
	pdf.test("Hello Prawn!")
end